[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/chainlink/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# CI Profile - optimized for GitHub Actions
[profile.ci]
src = "src/contracts"  # Only compile core contracts in CI
fuzz = { runs = 1000 }
invariant = { runs = 100 }
optimizer = true
optimizer_runs = 1000
via_ir = false

# Size optimization profile for deployment
[profile.size]
optimizer = true
optimizer_runs = 1        # Optimize for deployment size, not runtime gas
via_ir = true            # Use IR pipeline for better optimization
bytecode_hash = "none"   # Remove metadata hash to save bytes

# Aggressive size optimization
[profile.deploy]
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false    # Remove CBOR metadata
